### ISSUE TITLE
Provide access to the current contents of _gpsline in the fixCallback function

### ISSUE THREAD

**Issue by communig8-public** [electricimp/GPS#3]
This is an enhancement request.
If the current _gpsline contents were made available to the fixCallback function this would allow the code using this library to;
1) Implement handling code for GPS message types not yet supported by the library.
2) Allow for logging GPS messages as they arrive for debugging via server.log().
Thanks.

**Comment by betzrhodes** [comment]
We have updated the library, splitting it into a uart driver and a separate parser in version 1.0.0. These are breaking changes, but will allow for more flexibility parsing GPS messages and should address this issue. Thanks!
